### ISSUE TITLE
MacOS Python client not working

### ISSUE THREAD

**Issue by Imisrael** [griddb/python_client#28]
I have installed the python client via the releases file: [griddb_python-0.8.5-cp310-cp310-macosx_10_15_x86_64.whl](https://github.com/griddb/python_client/releases/download/0.8.5/griddb_python-0.8.5-cp310-cp310-macosx_10_15_x86_64.whl)

my environment: 

MacOS Monterey v12.6
Python: 3.10.8

The c-client was built on this machine from source.

Here is the error: 

```
$ python3 sample.py 239.0.0.1 31999 myCluster admin admin
Traceback (most recent call last):
  File "/private/tmp/sample.py", line 3, in <module>
    import griddb_python as griddb
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/griddb_python.py", line 21, in <module>
    import _griddb_python
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_[griddb_python.cpython-310-darwin.so](http://griddb_python.cpython-310-darwin.so/), 0x0002): symbol not found in flat namespace (_iconv)
```

**Comment by Imisrael** [comment]
I was actually able to solve the issue above. The issue was I needed to install the iconv library (via homebrew) and then add the library to my DYLD LIBRARY PATH. Once I did that, it worked.

$ echo $DYLD_LIBRARY_PATH
    /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
